import type { ElectrodeMaterial } from './types';

// 더미 데이터
const DUMMY_ELECTRODE_MATERIALS: ElectrodeMaterial[] = [
  // 양극재
  {
    id: 1,
    process: '전극',
    category: '양극재',
    type: 'NCM622',
    purpose: '개발',
    name: 'ME-6E2XP',
    spec: '10kg/bag',
    lotNo: 'CZ-ME6E2XP-24051401',
    company: 'EASPRING',
    origin: '해외',
    unit: 'kg',
    price: 0,
    note: '',
    stock: 10,
  },
  {
    id: 2,
    process: '전극',
    category: '양극재',
    type: 'NCM613',
    purpose: '개발',
    name: 'ME-6SC2',
    spec: '20kg/bag',
    lotNo: 'CZ-ME6SC2-22122703',
    company: 'EASPRING',
    origin: '해외',
    unit: 'kg',
    price: 79947,
    note: '',
    stock: 7,
  },
  {
    id: 3,
    process: '전극',
    category: '양극재',
    type: 'NCM613',
    purpose: '개발',
    name: 'ME-6SC5',
    spec: '20kg/bag',
    lotNo: 'CZ-ME6SC5-24053001',
    company: 'EASPRING',
    origin: '해외',
    unit: 'kg',
    price: 0,
    note: '',
    stock: 20,
  },
  {
    id: 4,
    process: '전극',
    category: '양극재',
    type: 'NCM622',
    purpose: '생산',
    name: 'NCM-622',
    spec: '20kg/bag',
    lotNo: 'NCM622-221007-01',
    company: '포스코케미칼',
    origin: '국내',
    unit: 'kg',
    price: 65000,
    note: '',
    stock: 6,
  },
  {
    id: 5,
    process: '전극',
    category: '양극재',
    type: 'NCM622',
    purpose: '생산',
    name: 'NCM-622',
    spec: '20kg/bag',
    lotNo: 'NCM622-0001-30',
    company: '포스코케미칼',
    origin: '국내',
    unit: 'kg',
    price: 65000,
    note: '',
    stock: 0,
  },
  {
    id: 6,
    process: '전극',
    category: '양극재',
    type: 'NCM811',
    purpose: '개발',
    name: 'ME-8E3S',
    spec: '20kg/bag',
    lotNo: 'CZ-ME8E3S-25100503',
    company: 'EASPRING',
    origin: '해외',
    unit: 'kg',
    price: 50918,
    note: '',
    stock: 0,
  },
  // 음극재
  {
    id: 7,
    process: '전극',
    category: '음극재',
    type: 'LTO',
    purpose: '생산',
    name: 'KP-T2',
    spec: '20kg/bag',
    lotNo: 'TE010-230211',
    company: 'KEDA',
    origin: '해외',
    unit: 'kg',
    price: 49294,
    note: '',
    stock: 69,
  },
  {
    id: 8,
    process: '전극',
    category: '음극재',
    type: 'LTO',
    purpose: '생산',
    name: 'KP-T2',
    spec: '25kg/bag',
    lotNo: 'TE011-231011-1',
    company: 'KEDA',
    origin: '해외',
    unit: 'kg',
    price: 45429,
    note: '',
    stock: 25,
  },
  {
    id: 9,
    process: '전극',
    category: '음극재',
    type: 'LTO',
    purpose: '생산',
    name: 'LTO-T30-D8',
    spec: '20kg/bag',
    lotNo: 'PT221007-01',
    company: '포스코케미칼',
    origin: '국내',
    unit: 'kg',
    price: 62000,
    note: '',
    stock: 20,
  },
  {
    id: 10,
    process: '전극',
    category: '음극재',
    type: 'LTO',
    purpose: '생산',
    name: 'T2',
    spec: '25kg/bag',
    lotNo: 'TE011-250401',
    company: 'BRT',
    origin: '해외',
    unit: 'kg',
    price: 46891,
    note: '',
    stock: 0,
  },
  {
    id: 11,
    process: '전극',
    category: '음극재',
    type: 'LTO',
    purpose: '개발',
    name: 'LTO-GEN4',
    spec: '15kg/bag',
    lotNo: 'AT80479',
    company: 'Altairnano',
    origin: '해외',
    unit: 'kg',
    price: 90000,
    note: '',
    stock: 30,
  },
  {
    id: 12,
    process: '전극',
    category: '음극재',
    type: 'LTO',
    purpose: '개발',
    name: '',
    spec: '20kg/bag',
    lotNo: '',
    company: '역신',
    origin: '해외',
    unit: 'kg',
    price: 70000,
    note: '',
    stock: 5,
  },
  {
    id: 13,
    process: '전극',
    category: '음극재',
    type: '천연흑연',
    purpose: '개발',
    name: 'PAS-A1',
    spec: '10kg/bag',
    lotNo: 'A200219002',
    company: '포스코케미칼',
    origin: '국내',
    unit: 'kg',
    price: 11025,
    note: '',
    stock: 1,
  },
  {
    id: 14,
    process: '전극',
    category: '음극재',
    type: '천연흑연',
    purpose: '개발',
    name: 'PAS-A1',
    spec: '20kg/bag',
    lotNo: 'A210718001-01',
    company: '포스코케미칼',
    origin: '국내',
    unit: 'kg',
    price: 11025,
    note: '',
    stock: 3.9,
  },
  {
    id: 15,
    process: '전극',
    category: '음극재',
    type: '천연흑연',
    purpose: '생산',
    name: 'PAS-C2',
    spec: '20kg/bag',
    lotNo: '00822110055B07J',
    company: '포스코케미칼',
    origin: '국내',
    unit: 'kg',
    price: 20000,
    note: '',
    stock: 32,
  },
  {
    id: 16,
    process: '전극',
    category: '음극재',
    type: '인조흑연',
    purpose: '생산',
    name: 'G56',
    spec: '25kg/bag',
    lotNo: '220605',
    company: '지천테크놀로지',
    origin: '해외',
    unit: 'kg',
    price: 17658,
    note: '',
    stock: 23,
  },
  // 집전체
  {
    id: 17,
    process: '전극',
    category: '집전체',
    type: 'Al Foil',
    purpose: '생산',
    name: 'A1100 H18(12㎛ x 230㎜)',
    spec: '12㎛ x 230㎜ x 2,000m/roll',
    lotNo: 'C2E4100006-21',
    company: '롯데인프라셀',
    origin: '국내',
    unit: 'm',
    price: 107,
    note: '',
    stock: 0,
  },
  {
    id: 18,
    process: '전극',
    category: '집전체',
    type: 'Al Foil',
    purpose: '생산',
    name: 'A1100 H18(10㎛ x 100㎜)',
    spec: '10㎛ x 100㎜ x 1,200m/roll',
    lotNo: 'PW0566-T0010',
    company: '삼아알루미늄',
    origin: '국내',
    unit: 'm',
    price: 77,
    note: '',
    stock: 1200,
  },
  {
    id: 19,
    process: '전극',
    category: '집전체',
    type: 'Al Foil',
    purpose: '생산',
    name: 'A1100 H18(12㎛ x 160㎜)',
    spec: '12㎛ x 160㎜ x 1,000m/roll',
    lotNo: 'PW2272-T0020',
    company: '삼아알루미늄',
    origin: '국내',
    unit: 'm',
    price: 96,
    note: '',
    stock: 3000,
  },
  {
    id: 20,
    process: '전극',
    category: '집전체',
    type: 'Al Foil',
    purpose: '생산',
    name: 'A1100 H18(12㎛ x 230㎜)',
    spec: '12㎛ x 230㎜ x 1,000m/roll',
    lotNo: 'PW0256-T0006',
    company: '삼아알루미늄',
    origin: '국내',
    unit: 'm',
    price: 134,
    note: '',
    stock: 2000,
  },
  {
    id: 21,
    process: '전극',
    category: '집전체',
    type: 'Al Foil',
    purpose: '생산',
    name: 'A1100 H18(12㎛ x 220㎜)',
    spec: '12㎛ x 220㎜ x 1,000m/roll',
    lotNo: 'PW3074-T004~08',
    company: '삼아알루미늄',
    origin: '국내',
    unit: 'm',
    price: 129,
    note: '',
    stock: 4000,
  },
  {
    id: 22,
    process: '전극',
    category: '집전체',
    type: 'Al Foil',
    purpose: '생산',
    name: 'A1100 H18(12㎛ x 105㎜)',
    spec: '12㎛ x 105㎜ x 1,000m/roll',
    lotNo: 'PW3074-T009-13',
    company: '삼아알루미늄',
    origin: '국내',
    unit: 'm',
    price: 61,
    note: '',
    stock: 8000,
  },
  {
    id: 23,
    process: '전극',
    category: '집전체',
    type: 'Al Foil',
    purpose: '생산',
    name: 'A1100 H18(10㎛ x 230㎜)',
    spec: '10㎛ x 230㎜ x 1,200m/roll',
    lotNo: 'PU0704-T0019',
    company: '삼아알루미늄',
    origin: '국내',
    unit: 'm',
    price: 825,
    note: '',
    stock: 4800,
  },
  {
    id: 24,
    process: '전극',
    category: '집전체',
    type: 'Al Foil',
    purpose: '개발',
    name: 'A1050-H18(15㎛ x 160㎜)',
    spec: '15㎛ x 160㎜ x 2,000m/roll',
    lotNo: 'L193111-067',
    company: '동일알루미늄',
    origin: '국내',
    unit: 'm',
    price: 120,
    note: '',
    stock: 2000,
  },
  {
    id: 25,
    process: '전극',
    category: '집전체',
    type: 'Al Foil',
    purpose: '생산',
    name: 'A1100 H18(10㎛ x 230㎜)',
    spec: '10㎛ x 230㎜ x 12,00m/roll',
    lotNo: 'PW1769',
    company: '삼아알루미늄',
    origin: '국내',
    unit: 'm',
    price: 0,
    note: '',
    stock: 4800,
  },
  {
    id: 26,
    process: '전극',
    category: '집전체',
    type: 'Al Foil',
    purpose: '생산',
    name: 'A1050-H18(15㎛ x 230㎜), 카본코팅',
    spec: '15㎛ x 230㎜ x 29,00m/roll',
    lotNo: '521-9-70-6-1',
    company: '동원시스템즈',
    origin: '국내',
    unit: 'm',
    price: 220,
    note: '',
    stock: 5800,
  },
  {
    id: 27,
    process: '전극',
    category: '집전체',
    type: 'Al Foil',
    purpose: '생산',
    name: 'A1100 H18(15㎛ x 160㎜)',
    spec: '15㎛ x 160㎜ x 1,200m/roll',
    lotNo: 'PW1653',
    company: '삼아알루미늄',
    origin: '국내',
    unit: 'm',
    price: 0,
    note: '',
    stock: 1200,
  },
  {
    id: 28,
    process: '전극',
    category: '집전체',
    type: 'Cu Foil',
    purpose: '생산',
    name: 'Cu Foil(8㎛ x 320㎜)',
    spec: '8㎛ x 320㎜ x 1,500m/roll',
    lotNo: '',
    company: '경동소재',
    origin: '국내',
    unit: 'm',
    price: 0,
    note: '',
    stock: 3000,
  },
  {
    id: 29,
    process: '전극',
    category: '집전체',
    type: 'Cu Foil',
    purpose: '생산',
    name: 'Cu Foil(6㎛ x 450㎜)',
    spec: '6㎛ x 450㎜ x 2,000m/roll',
    lotNo: '',
    company: '경동소재',
    origin: '국내',
    unit: 'm',
    price: 0,
    note: '',
    stock: 2000,
  },
  {
    id: 30,
    process: '전극',
    category: '집전체',
    type: 'Cu Foil',
    purpose: '생산',
    name: 'B-STN(10㎛ x 105㎜)',
    spec: '10㎛ x 105㎜ x 1,000m/roll',
    lotNo: 'SM3012025091007',
    company: 'SK넥실리스',
    origin: '국내',
    unit: 'm',
    price: 258,
    note: '',
    stock: 0,
  },
];

export const getElectrodeMaterials = async (isZeroStock: boolean = false): Promise<ElectrodeMaterial[]> => {
  // 실제 API 호출로 변경할 예정
  // return await api.get('/material/electrode', { params: { isZeroStock } });
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(DUMMY_ELECTRODE_MATERIALS);
    }, 500);
  });
};

export const createElectrodeMaterial = async (material: Omit<ElectrodeMaterial, 'id'>) => {
  // 실제 API 호출
  // return await api.post('/stock/electrode', material);
  console.log('생성:', material);
};

export const updateElectrodeMaterial = async (id: number, material: Partial<ElectrodeMaterial>) => {
  // 실제 API 호출
  // return await api.put(`/stock/electrode/${id}`, material);
  console.log('수정:', id, material);
};

export const deleteElectrodeMaterial = async (id: number) => {
  // 실제 API 호출
  // return await api.delete(`/stock/electrode/${id}`);
  console.log('삭제:', id);
};
