import type { Row } from './MaterialNew';

export const initialIds = Array.from({ length: 14 }, (_, i) => i + 1);

export const initialRows: Row[] = [
  {
    id: 1,
    classification: 'Cathode',
    category: '양극재',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },
  {
    id: 2,
    classification: 'Cathode',
    category: '도전재',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },
  {
    id: 3,
    classification: 'Cathode',
    category: '바인더',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },
  {
    id: 4,
    classification: 'Cathode',
    category: '집전체',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },
  {
    id: 5,
    classification: 'Cathode',
    category: '용매',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },

  {
    id: 6,
    classification: 'Anode',
    category: '음극재',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },
  {
    id: 7,
    classification: 'Anode',
    category: '도전재',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },
  {
    id: 8,
    classification: 'Anode',
    category: '바인더',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },
  {
    id: 9,
    classification: 'Anode',
    category: '집전체',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },
  {
    id: 10,
    classification: 'Anode',
    category: '용매',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },

  {
    id: 11,
    classification: 'Assembly',
    category: '분리막',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },
  {
    id: 12,
    classification: 'Assembly',
    category: '리드탭',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },
  {
    id: 13,
    classification: 'Assembly',
    category: '파우치',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },
  {
    id: 14,
    classification: 'Assembly',
    category: '전해액',
    materialType: '',
    model: '',
    company: '',
    unit: '',
    quantity: '',
  },
];
