import type { DrawingLedgerItem } from './DrawingLedgerTypes';

export const MOCK_DRAWING_LEDGER: DrawingLedgerItem[] = [
  { id: 1, category: '공장', registeredDate: '190806', projectName: '오산 공장 건물 Layout', drawingNo: 'Eurocell-FD01', version: 'V1.0', description: '오산 공장 건물 배치 도면' },
  { id: 2, category: '공장', registeredDate: '200221', projectName: '오산 공장 내부 Layout', drawingNo: 'Eurocell-FD02', version: 'V1.0', description: '오산 공장 내부 설비 Layout' },
  { id: 3, category: '공장', registeredDate: '230522', projectName: '오산 공장 충방전실 Layout', drawingNo: 'Eurocell-FD03', version: 'V1.0', description: '오산 공장 대형 충방전실 설비 Layout' },
  { id: 4, category: '공장', registeredDate: '231026', projectName: '오산 공장 드라이룸 Layout', drawingNo: 'Eurocell-FD04', version: 'V1.0', description: '오산 공장 2층 드라이룸 설비 Layout' },
  { id: 5, category: '설비', registeredDate: '210409', projectName: 'Pouch 단동 설비 (유진테크놀로지)', drawingNo: '유진-MC01', version: 'V1.0', description: '단동 Notching MC' },
  { id: 6, category: '설비', registeredDate: '210409', projectName: 'Pouch 단동 설비 (유진테크놀로지)', drawingNo: '유진-MC02', version: 'V1.0', description: 'Pouch forming MC' },
  { id: 7, category: '설비', registeredDate: '210409', projectName: 'Pouch 단동 설비 (유진테크놀로지)', drawingNo: '유진-MC03', version: 'V1.0', description: 'Top & Side sealing MC' },
  { id: 8, category: '설비', registeredDate: '210409', projectName: 'Pouch 단동 설비 (유진테크놀로지)', drawingNo: '유진-MC04', version: 'V1.0', description: 'V-sealing MC' },
  { id: 9, category: '설비', registeredDate: '210409', projectName: 'Pouch 단동 설비 (유진테크놀로지)', drawingNo: '유진-MC05', version: 'V1.0', description: '각형 Cell Ball & Degas MC' },
  { id: 10, category: '설비', registeredDate: '210409', projectName: 'Pouch 단동 설비 (유진테크놀로지)', drawingNo: '유진-MC06', version: 'V1.0', description: 'Pouch EL-Filling MC' },
  { id: 11, category: '설비', registeredDate: '210409', projectName: 'Pouch 단동 설비 (유진테크놀로지)', drawingNo: '유진-MC02_Mold', version: 'V1.0', description: 'Pouch forming MOLD' },
  { id: 12, category: '설비', registeredDate: '231122', projectName: 'Slot Die shim Design', drawingNo: 'Slot die shim-01', version: 'V1.0', description: 'Slot Die shim 설계 도면' },
  { id: 13, category: '제품', registeredDate: '230405', projectName: 'NFP1_UFC-L20B', drawingNo: 'NFP1_PD01', version: 'V1.0', description: 'UFC-L20B 양산형 제품 도면' },
  { id: 14, category: '제품', registeredDate: '230405', projectName: 'UHC-INR21700', drawingNo: 'UHC-INR21700_PD01', version: 'V1.0', description: 'UHC-INR21700 전극 공정 도면' },
  { id: 15, category: '제품', registeredDate: '241014', projectName: 'UFC-L20B', drawingNo: 'UFC-L20B_PD01', version: 'V2.0', description: 'UFC-L20B 개발 제품 도면' },
  { id: 16, category: 'OEM/ODM', registeredDate: '240130', projectName: 'KORCHIP 중국 공장_전극 도면', drawingNo: 'KCDE022269B1_PD01', version: 'V1.0', description: '전극 공정 도면' },
  { id: 17, category: 'OEM/ODM', registeredDate: '240312', projectName: 'KORCHIP 중국 공장_Layout', drawingNo: 'KCDE022269B1_L01', version: 'V1.0', description: '중국 창주 공장 Layout' },
  { id: 18, category: '설비', registeredDate: '240930', projectName: 'Pouch 단동 설비 (유진테크놀로지)', drawingNo: '유진-MC03_Mold', version: 'V1.0', description: 'Top sealing bar mold' },
  { id: 19, category: 'OEM/ODM', registeredDate: '250206', projectName: '6T Cell Project (Forming MC)', drawingNo: 'HYTC-MC01', version: 'V1.0', description: 'Pouch Forming MC & Mold (HYTC)' },
  { id: 20, category: 'OEM/ODM', registeredDate: '250218', projectName: '6T Cell Project (Sealing MC)', drawingNo: '한엔지니어링-MOLD', version: 'V1.0', description: 'Top & Side sealing bar mold' },
  { id: 21, category: 'OEM/ODM', registeredDate: '250218', projectName: '6T Cell Project (Stacking MC)', drawingNo: '한엔지니어링-UNIT', version: 'V1.0', description: 'Stack Unit Parts' },
  { id: 22, category: 'OEM/ODM', registeredDate: '250218', projectName: '6T Cell Project (Welding MC)', drawingNo: '한엔지니어링-JIG', version: 'V1.0', description: 'Welding JIG' },
  { id: 23, category: 'OEM/ODM', registeredDate: '250218', projectName: '6T Cell Project (Sealing MC)', drawingNo: '한엔지니어링-JIG', version: 'V1.0', description: 'Sealing JIG' },
  { id: 24, category: 'OEM/ODM', registeredDate: '250218', projectName: '6T Cell Project (Cutting)', drawingNo: '한엔지니어링-JIG', version: 'V1.0', description: 'Top & Side Cutting JIG' },
  { id: 25, category: '제품', registeredDate: '250620', projectName: 'UFC-L38C', drawingNo: 'UFC-L38C_PD01', version: 'V1.0', description: 'UFC-L38C 제품 전극 공정 도면' },
  { id: 26, category: '제품', registeredDate: '250925', projectName: 'UFC-L38C', drawingNo: 'UFC-L38C_PD01', version: 'V1.0', description: 'UFC-L38C_V5.8 전 공정 도면' },
  { id: 27, category: '설비', registeredDate: '251104', projectName: 'Pouch 단동 설비 (유진테크놀로지)', drawingNo: '유진-MC03', version: 'V2.0', description: 'Top sealing bar' },
];
